language: cpp

before_install:
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update -qq
 - sudo apt-get -qq install boost1.55 
 - sudo apt-get install lua5.1 liblua5.1-dev

script:
  - make -C Build config=release
